CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL);

CREATE TABLE wallet
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acc_id   BIGINT                NOT NULL,
    currency VARCHAR(255)          NOT NULL,
    amount   DECIMAL(21) DEFAULT 0 NOT NULL
);
CREATE TABLE transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_acc_id BIGINT NOT NULL,
    to_acc_id BIGINT NOT NULL,
    currency VARCHAR(255) NOT NULL,
    amount DECIMAL(21) NOT NULL);

CREATE TABLE client (
    id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    second_name VARCHAR(255) NOT NULL,
    patronymic VARCHAR(255),
    phone_number VARCHAR(255),
    email VARCHAR(255));

ALTER TABLE account
    ADD CONSTRAINT account_user_id_fk
    FOREIGN KEY (user_id)
    REFERENCES client (id)
    ON DELETE NO ACTION
       ON UPDATE NO ACTION;

ALTER TABLE wallet
    ADD CONSTRAINT wallet_account_id_fk
    FOREIGN KEY (acc_id)
    REFERENCES account (id)
    ON DELETE NO ACTION
       ON UPDATE NO ACTION;
